
version: "3.9"  # optional since v1.27.0
services:
  api:
    build:
      context: ./backend
      dockerfile: dockerfile.local
    volumes:
      - ./backend:/root/app/
      - ./backend:/home/django/app/
  jsreport:
    build: 
      context: jsreport
      dockerfile: dockerfile
    volumes:
      - ./jsreport/data:/app/data
      # - ./reports/app/:/app/
  report-service:
    build:
      context: ReportService
      dockerfile: dockerfile
    volumes:
      - ./ReportService/src/:/app/src/
    