version: "3.9"  # optional since v1.27.0
services:
  api:
    ports:
      - "8000:8000"
    environment:
      ADMIN_URL: admin/
      DATABASE_URL: ${DB_URL}
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mariadb:10.7.1
    environment:
      MYSQL_ROOT_PASSWORD: ${db_pass}
      MYSQL_DATABASE: coderatbest
    volumes:
      - database:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 
volumes:
  database: {}