version: "3.9"  # optional since v1.27.0
services:
  api:
    build:
      context: ./backend
      dockerfile: dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/home/django/app/
    environment:
      ADMIN_URL: admin
      DATABASE_URL: ${DB_URL}
    depends_on:
      - db
  db:
    image: mariadb:10.7.1
    environment:
      MYSQL_ROOT_PASSWORD: ${db_pass}
      MYSQL_DATABASE: coderatbest
volumes:
  logvolume01: {}