
version: "3.9"  # optional since v1.27.0
services:
  api:
    build:
      context: ./backend
      dockerfile: dockerfile.local
    volumes:
      - ./backend:/root/app/
      - ./backend:/home/django/app/
  jsreport:
    build: 
      context: reports
      dockerfile: dockerfile
    volumes:
      # - ./reports/data:/app/data
      - ./reports/app/:/app/
    