FROM python:3.9.5

RUN useradd -ms /bin/bash django
USER django
WORKDIR /home/django/app/

RUN python -m pip install --upgrade pip
COPY --chown=django:django requirements.txt .
RUN pip install -r requirements.txt

COPY --chown=django:django . .
RUN chmod a+x start.sh
CMD [ "./start.sh" ]