FROM python:3.9.5

RUN useradd -ms /bin/bash django

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE 1

USER root
WORKDIR /root/app/

RUN python -m pip install Pillow

COPY requirements.txt .
COPY requirements.prod.txt .
RUN pip install -r requirements.txt
RUN pip install -r requirements.prod.txt

COPY . .
RUN chmod a+x entripoint.sh
CMD [ "./entripoint.sh","USER=root"  ]