FROM jsreport/jsreport:3.4.1
WORKDIR /app
# RUN npm i handlebars-intl --save
COPY --chown=jsreport:jsreport /app/ /app/
RUN npm install
ENV httpPort=3000
EXPOSE 5488
# ENTRYPOINT [ "tail" ]
# CMD [ "-f","/dev/null" ]