# Generated by Django 3.2.8 on 2022-02-04 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220203_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='imgs_extra',
        ),
        migrations.AddField(
            model_name='imagesprofile',
            name='imgs_extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='imagesprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/profile/imgs_extra'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/profile/', verbose_name='profile picture'),
        ),
    ]
