# Generated by Django 3.2.8 on 2022-02-04 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220204_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesprofile',
            old_name='imgs_extra',
            new_name='profile',
        ),
    ]
