# Generated by Django 3.2.8 on 2022-02-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_imgs_extra_imagesprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/profile/imgs_extra', verbose_name='extra image'),
        ),
    ]
