# Generated by Django 3.2.8 on 2022-02-05 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_imagesprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLineProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=300, null=True)),
                ('icon', models.CharField(max_length=20)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
