# Generated by Django 3.2.8 on 2022-02-05 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_timelineprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesprofile',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_profile', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='timelineprofile',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_line_profile', to='users.profile'),
        ),
    ]
